import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import type { ReactNode } from "react";
// import { SessionProvider } from "next-auth/react";
// import { auth } from "@/lib/auth";

// import { Provider } from "@/component/provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="ja" suppressHydrationWarning>
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<MantineProvider>
					{/* <Provider>{children}</Provider> */}
					{children}
				</MantineProvider>
			</body>
		</html>
	);
}
